### ISSUE TITLE
Output format of arrays in Sass maps

### ISSUE THREAD

**Issue by tomdavies** [MathiasPaumgarten/grunt-shared-config#28]
`getStyleSafeValue` doesn't produce the expected output for arrays when output to the value of a key in a Sass `map`

Consider this source data:

```json
// with options.name = 'grids' & options.useSassMaps = true
{
    "base": {
        "gutter": 15,
        "columns": 12,
        "output": [ 2, 10, 12 ]
    }
};
```

This currently results in the Sass output:

```scss
$grids: (
	base: (
		gutter: 15,
		columns: 12,
		output: 2,10,12
	)
);

```

This will cause a parse error in Sass, as `,` is used both as a `list` separator, and to denote the end of a `map` key's value.

The expected output would wrap list/array output in parens to avoid this ambiguity:

```scss
$grids: (
	base: (
		gutter: 15,
		columns: 12,
		output: (2,10,12)
	)
);

```

Happy to take a crack at this one if a PR would be considered, but #25 suggests you're looking refactoring `getStyleSafeValue` anyway, so thought I'd open an issue first.

**Comment by MathiasPaumgarten** [comment]
Hey there,

thanks for taking a look at this. I kind of responded to this on #25. Let me know if this works for you. Maybe we can merge these two issues into one. Otherwise if you open an PR, reference this issue, then I will close this and keep the conversation going on the PR. 

Thanks for the interest in `grunt-shared-config`
